export const EXPORT_BOOKMARKS = 'EXPORT_BOOKMARKS'
export const EXPORT_BOOKMARKS_SUCCESS = 'EXPORT_BOOKMARKS_SUCCESS'
export const IMPORT_BOOKMARKS = 'IMPORT_BOOKMARKS'
export const IMPORT_BOOKMARKS_SUCCESS = 'IMPORT_BOOKMARKS_SUCCESS'
