name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Prisma generate
        run: yarn prisma generate
      - name: Test
        run: yarn test
        env:
          APP_URL: http://localhost:3000
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          SITE_ENV: prod
