name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: docker-compose up -d
        run: cd webapp && docker-compose up -d
      - name: docker ps -a
        run: docker ps -a
      - name: Prisma migrate
        run: yarn prisma migrate dev
        env:
          DATABASE_URL: postgres://clip:password@localhost:5433/clip
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          SITE_ENV: prod
