name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn
      - name: docker-compose up -d
        run: cd webapp && docker-compose up -d
      - name: docker ps -a
        run: docker ps -a
      - name: Prisma migrate
        run: yarn prisma migrate dev
        env:
          DATABASE_URL: postgres://clip:password@localhost:5433/clip
      - name: Run unit tests
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          SITE_ENV: prod
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: webapp
          start: yarn ci
        env:
          DATABASE_URL: postgres://clip:password@localhost:5433/clip
