name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXT_PUBLIC_SITE_ENV: ${{ secrets.NEXT_PUBLIC_SITE_ENV }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/webapp/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          SITE_ENV: prod
      - name: Type check
        run: yarn tsc
        with:
          working-directory: webapp
      - name: docker-compose up -d
        run: cd webapp && docker-compose up -d
      - name: docker ps -a
        run: docker ps -a
      - name: Prisma migrate
        run: yarn prisma migrate deploy
      - name: Run unit tests
        run: yarn test
      - name: Run e2e tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: webapp
          start: yarn ci
          browser: firefox
